### ISSUE TITLE
LabScripts GeneralTracing UnboundLocalError in SummarizeData.py

### ISSUE THREAD

**Issue by CalebRouleau** [google/UIforETW#101]
Traceback (most recent call last):\r\r\n  File "SummarizeData.py", line 123, in <module>\r\r\n    sys.exit(main())\r\r\n  File "SummarizeData.py", line 113, in main\r\r\n    [\'dwm.exe\', \'csrss.exe\'], \'GPU usage\', \'ms\', results)\r\r\n  File "SummarizeData.py", line 102, in Summarize\r\r\n    \'value\' : other_process})\r\r\nUnboundLocalError: local variable \'other_process\' referenced before assignment\r\r\n

I have a fix that I will send soon

**Comment by randomascii** [comment]
Weird. It looks like that should only happen if there are no other processes that use CPU time, which seems like some sort of fantastical crazy land. I wonder if that is actually what happened or if something in the trace processing broke.

Either way, not crashing would be good.
